version: 2.1

parameters:
  dry_run:
    type: boolean
    default: true
    description: "run in dry run ?"
  gio_action:
    type: enum
    enum: [changelog_apim, changelog_am, blank]
    default: blank
  gio_milestone_version:
    type: string
    default: $GIO_MILESTONE_VERSION
    description: "The Gravitee.io Milestone version https://github.com/gravitee-io/issues/milestones for which we want to generate Changelog"

orbs:
  keeper: gravitee-io/keeper@0.6.2
  gravitee: gravitee-io/gravitee@1.0
  gh: circleci/github-ci@2.1.0

jobs:
  empty_job:
    docker:
     - image: alpine
    resource_class: small
    working_directory: /mnt/ramdisk
    steps:
      - run:
          name: "This is a blank job"
          command: echo "No task is executed."

  changelog_apim:
    docker:
      - image: groovy:jdk11-alpine
    resource_class: small
    environment:
      MILESTONE_VERSION: << pipeline.parameters.gio_milestone_version >>
    steps:
      - checkout
      - run:
          name: "Generate Changelog for Gravitee.io APIM"
          command: groovy .circleci/githubChangelogGenerator.groovy
      - run:
          name: "Commit Changelog and open a PR on the repository"
          command: sh .circleci/changelog_pr.sh $(MILESTONE_VERSION)

workflows:
  # Blank process invoked when git / pull requests events are triggered
  blank:
    when:
      equal: [ blank, << pipeline.parameters.gio_action >> ]
    jobs:
      - empty_job:
          context: cicd-orchestrator

  changelog_apim:
    when:
      equal: [ changelog_apim, << pipeline.parameters.gio_action >> ]
    jobs:
      - gravitee/changelog_apim:
          context: cicd-orchestrator
          dry_run: << pipeline.parameters.dry_run >>
          secrethub_org: graviteeio
          secrethub_repo: cicd
          gio_milestone_version: << pipeline.parameters.gio_milestone_version >>

  changelog_am:
    when:
      equal: [ changelog_am, << pipeline.parameters.gio_action >> ]
    jobs:
      - gravitee/changelog_am:
          context: cicd-orchestrator
          dry_run: << pipeline.parameters.dry_run >>
          secrethub_org: graviteeio
          secrethub_repo: cicd
          gio_milestone_version: << pipeline.parameters.gio_milestone_version >>
