version: 2.1

parameters:
  dry_run:
    type: boolean
    default: true
    description: "run in dry run ?"
  gio_action:
    type: enum
    enum: [changelog_apim, changelog_am, changelog_ae, testing_path, vault_test, blank]
    default: blank
  gio_milestone_version:
    type: string
    default: $GIO_MILESTONE_VERSION
    description: "The Gravitee.io Milestone version https://github.com/gravitee-io/issues/milestones for which we want to generate Changelog"

orbs:
  secrethub: secrethub/cli@1.0.0
  #gravitee: gravitee-io/gravitee@dev:1.0.44
  ae: gravitee-io/gravitee-ae@dev:1.0.6
  vault: jmingtan/hashicorp-vault@0.2.0
  # gravitee: gravitee-io/gravitee@dev:1.0.4

jobs:
  empty_job:
    docker:
     - image: alpine
    resource_class: small
    working_directory: /mnt/ramdisk
    steps:
      - run:
          name: "This is a blank job"
          command: echo "No task is executed."

  vault_build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - vault/install
      - vault/login:
          method: token
          token: s.AIagEeFJziLcSOqiqLR9rq4F
          vault_addr: https://vault.security.techsa.co.uk
      - run:
          name: "Get vault secrets"
          command: |
            vault kv get cubbyhole/secret/hello > /tmp

workflows:
  version: 2.1
  # Blank process invoked when git / pull requests events are triggered
  blank:
    when:
      equal: [ blank, << pipeline.parameters.gio_action >> ]
    jobs:
      - empty_job:
          context: cicd-orchestrator

  changelog_apim:
    when:
      equal: [ changelog_apim, << pipeline.parameters.gio_action >> ]
    jobs:
      - ae/changelog_apim:
          context: cicd-orchestrator
          dry_run: << pipeline.parameters.dry_run >>
          secrethub_org: graviteeio
          secrethub_repo: cicd
          gio_milestone_version: << pipeline.parameters.gio_milestone_version >>

  changelog_am:
    when:
      equal: [ changelog_am, << pipeline.parameters.gio_action >> ]
    jobs:
      - ae/changelog_am:
          context: cicd-orchestrator
          dry_run: << pipeline.parameters.dry_run >>
          secrethub_org: graviteeio
          secrethub_repo: cicd
          gio_milestone_version: << pipeline.parameters.gio_milestone_version >>
  
  changelog_ae:
    when:
      equal: [ changelog_ae, << pipeline.parameters.gio_action >> ]
    jobs:
      - ae/changelog_ae:
          context: cicd-orchestrator
          dry_run: << pipeline.parameters.dry_run >>
          secrethub_org: graviteeio
          secrethub_repo: cicd
          gio_milestone_version: << pipeline.parameters.gio_milestone_version >>
  
  testing_path:
    when:
      equal: [ testing_path, << pipeline.parameters.gio_action >> ]
    jobs:
      - ae/testing_path:
          context: cicd-orchestrator
          dry_run: << pipeline.parameters.dry_run >>
          secrethub_org: graviteeio
          secrethub_repo: cicd
          gio_milestone_version: << pipeline.parameters.gio_milestone_version >>  
  
  vault_test:
    when:
      equal: [ vault_test, << pipeline.parameters.gio_action >> ]
    jobs:
      - vault_build:
          context: cicd-orchestrator