version: 2.1

parameters:
  dry_run:
    type: boolean
    default: true
    description: "run in dry run ?"
  gio_action:
    type: enum
    enum: [changelog_apim, changelog_am, changelog_ae, testing_path, vault_test, blank]
    default: blank
  gio_milestone_version:
    type: string
    default: $GIO_MILESTONE_VERSION
    description: "The Gravitee.io Milestone version https://github.com/gravitee-io/issues/milestones for which we want to generate Changelog"

orbs:
  secrethub: secrethub/cli@1.0.0
  #gravitee: gravitee-io/gravitee@dev:1.0.44
  ae: gravitee-io/gravitee-ae@dev:1.0.6
  vault: jmingtan/hashicorp-vault@0.2.0
  # gravitee: gravitee-io/gravitee@dev:1.0.4

jobs:
  empty_job:
    docker:
     - image: alpine
    resource_class: small
    working_directory: /mnt/ramdisk
    steps:
      - run:
          name: "This is a blank job"
          command: echo "No task is executed."

  vault_build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - run:
          name: install vault

          command:  |
            apk add --no-cache vault
          #command:  |
           # curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
            #sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
           # sudo apt-get update && sudo apt-get install vault
     # - run:
      #    name: "Re-format GPG Keys"
       #   command: |
        #    # Re-format private and public GPG Keys
         #   export PUB_KEY_CONTENT=$(cat /tmp/gravit33bot/.secrets/.gungpg/graviteebot.gpg.pub.key | awk -F '-----BEGIN PGP PUBLIC KEY BLOCK-----' '{print $2}' | awk -F '-----END PGP PUBLIC KEY BLOCK-----' '{print $1}')
          #  echo '-----BEGIN PGP PUBLIC KEY BLOCK-----' > /tmp/gravit33bot/.secrets/.gungpg/graviteebot.gpg.pub.key
         #   echo "$PUB_KEY_CONTENT" | tr ' ' '\n' | tee -a /tmp/gravit33bot/.secrets/.gungpg/graviteebot.gpg.pub.key
          #  sed -i '$ s/$/-----END PGP PUBLIC KEY BLOCK-----/' /tmp/gravit33bot/.secrets/.gungpg/graviteebot.gpg.pub.key
           # export PRIV_KEY_CONTENT=$(cat /tmp/gravit33bot/.secrets/.gungpg/graviteebot.gpg.priv.key | awk -F '-----BEGIN PGP PRIVATE KEY BLOCK-----' '{print $2}' | awk -F '-----END PGP PUBLIC KEY BLOCK-----' '{print $1}')
          #  echo '-----BEGIN PGP PRIVATE KEY BLOCK-----' > /tmp/gravit33bot/.secrets/.gungpg/graviteebot.gpg.priv.key
           # echo "$PRIV_KEY_CONTENT" | tr ' ' '\n' | tee -a /tmp/gravit33bot/.secrets/.gungpg/graviteebot.gpg.priv.key
            #sed -i '$ s/$/-----END PGP PRIVATE KEY BLOCK-----/' /tmp/gravit33bot/.secrets/.gungpg/graviteebot.gpg.priv.key
      #- gravitee/generate_s3cmd_config:
       #   path_to_aws_access_key_file: '/tmp/gravit33bot/.secrets/.s3cmd/aws_access_key'
        #  path_to_aws_secret_key_file: '/tmp/gravit33bot/.secrets/.s3cmd/aws_secret_key'
         # path_to_generated_file: '/tmp/gravit33bot/.secrets/.s3cmd/config'

      - run:
          name: login vault
          command:  |
            export VAULT_ADDR=https://vault.security.techsa.co.uk
            vault login s.AIagEeFJziLcSOqiqLR9rq4F
      - run:
          name: "Get vault secrets"
          command: |
            vault kv get cubbyhole/secret/hello > /tmp

workflows:
  version: 2.1
  # Blank process invoked when git / pull requests events are triggered
  blank:
    when:
      equal: [ blank, << pipeline.parameters.gio_action >> ]
    jobs:
      - empty_job:
          context: cicd-orchestrator

  changelog_apim:
    when:
      equal: [ changelog_apim, << pipeline.parameters.gio_action >> ]
    jobs:
      - ae/changelog_apim:
          context: cicd-orchestrator
          dry_run: << pipeline.parameters.dry_run >>
          secrethub_org: graviteeio
          secrethub_repo: cicd
          gio_milestone_version: << pipeline.parameters.gio_milestone_version >>

  changelog_am:
    when:
      equal: [ changelog_am, << pipeline.parameters.gio_action >> ]
    jobs:
      - ae/changelog_am:
          context: cicd-orchestrator
          dry_run: << pipeline.parameters.dry_run >>
          secrethub_org: graviteeio
          secrethub_repo: cicd
          gio_milestone_version: << pipeline.parameters.gio_milestone_version >>
  
  changelog_ae:
    when:
      equal: [ changelog_ae, << pipeline.parameters.gio_action >> ]
    jobs:
      - ae/changelog_ae:
          context: cicd-orchestrator
          dry_run: << pipeline.parameters.dry_run >>
          secrethub_org: graviteeio
          secrethub_repo: cicd
          gio_milestone_version: << pipeline.parameters.gio_milestone_version >>
  
  testing_path:
    when:
      equal: [ testing_path, << pipeline.parameters.gio_action >> ]
    jobs:
      - ae/testing_path:
          context: cicd-orchestrator
          dry_run: << pipeline.parameters.dry_run >>
          secrethub_org: graviteeio
          secrethub_repo: cicd
          gio_milestone_version: << pipeline.parameters.gio_milestone_version >>  
  
  vault_test:
    when:
      equal: [ vault_test, << pipeline.parameters.gio_action >> ]
    jobs:
      - vault_build:
          context: cicd-orchestrator